version: 2.1
jobs:
    docker: 
      - image: circleci/node:4.8.2 
    build:
      steps:
        - checkout 
        - run: echo "hello world"
    test:
      steps:
        - checkout
        - run: echo "Hellooo!!"
     workflows:
     version: 2.1
      build_and_test:
        jobs:
          - build
          - test
        
