version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world"
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "Helloooo!!!"
workflows:
  version: 2.1
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "24 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
            
        
